#!/usr/bin/env bash
#Install nginx

apt-get update
apt-get install -y nginx
rm /var/www/html*.html
touch /var/www/html/index.html
touch /var/www/html/404.html
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /var/www/html;
    index   index.html;
    location /redirect_me {
        return 301 http://opticspc.tech/;
    }
    error_page 404 /404.html;
    location /404 {
        root /var/www/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
