#!/usr/bin/env bash
#Displays To infinity and beyond indefinitly
#With sleep 2 in between each iteration.
# Display I am invincible when recieving a SIGTERM 

trap 'echo "I am invincible!!!"' 15
while true 
do 
	echo "To infinity and beyond" 
	sleep 2 
done
