#!/usr/bin/env bash
###Display Best School 10 times and then hi in the 9th spot
i=1
while [ $i -le 10 ]

do
	if [ $i = 9 ]
	then
	echo "Best School
Hi"
	else
	echo "Best School"
	fi
	((i++))
   done
   export i
