#!/usr/bin/env bash
###Display bad luck good luck Best School

i=0
while (( i++ < 10 ))
do
    if (( i == 4 ))
    then
	echo 'bad luck'
    elif (( i == 8 ))
    then
	echo 'good luck'
    else
	echo 'Best School'
    fi
done
