#!/usr/bin/env bash
#Display the time for 12 hours and 59 minutes
##Display the hours from 0-12
###Display the minutes from 1-59

hour=0

while [ $hour -le 12]
do
  echo "Hour: $hour"
  minute=1
  while [ minute -le 12 ]
  do
	echo "$minute"
	(( minute++ ))
done
