#!/usr/bin/env bash
#Install nginx

apt-get update
apt-get install -y nginx
rm /etc/nginx/html*.html
touch /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Hello World" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
printf %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /var/www/html;
    index   index.html;
    add_header X-Served-By $HOSTNAME;
    location /redirect_me {
    }
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default
service nginx restart
