#!/usr/bin/env bash
#Install nginx

apt-get update
apt-get -y install haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
cat <<EOT > /etc/haproxy/haproxy.cfg
defaults
    mode    http
frontend http-in
    bind    *:80
    default_backend questionTwo
backend questionTwo
    balance roundrobin
    server 5581-web-01 35.180.251.8 check
    server 5581-web-02 15.236.55.179 check
EOT
sudo service haproxy restart
